### ISSUE TITLE
add to favourites list PDP

### ISSUE THREAD

**Issue by elisabethschneider** [commercetools/commercetools-sunrise-java#123]
Customer should be able to add products to his favorites without being sign in or having an account.  This is practically the wishlist.
From this list he should be able to add product to the cart. More info on the actual page

**Comment by butenkor** [comment]
How should user be able to see his wishlist on 2 different browsers without sign in? For wishlist i think you have to be signed in.

**Comment by trangng** [comment]
@butenkor no customer don't need to be signed in. you should be able to save it via cookies.
if he opens it in another browser it's not here, only if he saved it in his account.

**Comment by butenkor** [comment]
What is the point of wishlist if it's gone after you close your browser or you different one? This functionality is already there if you use anonymous cart.

**Comment by trangng** [comment]
@butenkor because It's the new way to be able to browse products and putting them in your favourites list. putting in the cart is not the right way to save your products you might like, because you're probably still not sure if you want it or not. Imagine the scenario you're browsing on the POP with 600 products. For now you just want to save products in you favourites list so you can look in detail at each product later when you finished with browsing all 600 products. Then from the favourites list you can easily open the product in a quick view and products can be added one by one or all at once. By forcing customers to register or using cart is not an optimal user experience.

**Comment by butenkor** [comment]
What happens with wishlist if you login? Will it be persisted an customers account or still be cookie based? What happens to cookie based wishlist if you login and already have existing wishlist on your customer account?
