### ISSUE TITLE
Remove hardcoded image paths in ProductOverviewPageController?

### ISSUE THREAD

**Issue by selo-ecube** [commercetools/commercetools-sunrise-java#412]
Is it possible to remove the hardcoded image paths on [lines 147 and 148 of ProductOverviewPageController](https://github.com/commercetools/commercetools-sunrise-java/blob/master/product-catalog/app/productcatalog/productoverview/ProductOverviewPageController.java#L147 )?

```
bannerBean.setImageMobile("/assets/img/banner_mobile-0a9241da249091a023ecfadde951a53b.jpg"); // TODO obtain from category?
bannerBean.setImageDesktop("/assets/img/banner_desktop-9ffd148c48068ce2666d6533b4a87d11.jpg"); // TODO obtain from category?
```

To me it seems that the image paths should be in the theme. They caused us trouble because we at times build the theme without fingerprinting - in that case the hard-coded image sources are incorrect.

We changed [input/templates/partials/catalog/pop/banner.hbs in commercetools-sunrise-theme](https://github.com/commercetools/commercetools-sunrise-theme/blob/master/input/templates/partials/catalog/pop/banner.hbs) to the following to be able to remove the hardcoded image paths.

```
<figure class="figure-banner">
  <img class="img-responsive hidden-sm hidden-md hidden-lg" src="{{@root.meta.assetsPath}}img/banner_mobile.jpg" alt="{{banner.title}}">
  <img class="img-responsive hidden-xs" src="{{@root.meta.assetsPath}}img/banner_desktop.jpg" alt="{{banner.title}}">
  <figcaption class="figcaption-banner-text">
    <h2>{{banner.title}}</h2>
    <h3>{{{banner.description}}}</h3>
  </figcaption>
</figure>
```

There is this `// TODO obtain from category?` comment next to the image paths - maybe it could remain there and be clarified that at this position a future version of the shop might obtain image paths from the category.

I'm not sure whether this change would also affect https://github.com/sphereio/commercetools-sunrise-php as it might use the sunrise-theme as well.

**Comment by lauraluiz** [comment]
@selo-ecube the problem is that these pictures as they are thought from Sunrise requirements are supposedly coming from the category info. But categories in CTP don't come with a default image information and we cannot use custom fields. That's why temporarily they are hardcoded but we are expecting this functionality in the platform to properly work, that's the reason for the TODOs.

Anyway, what the default Sunrise theme and default Sunrise behaviour does should not affect what you do. You should be able to override everything that works differently. If that's not the case then please report it, but from what I understand, you could override it in your app.

Thanks for the warning, but unfortunately we are aware of it and waiting for a proper solution :)
