### ISSUE TITLE
MoneyContext.of(currency, userContext.locale()) receives "de" as locale -> no currency symbol for euro

### ISSUE THREAD

**Issue by fhaertig** [commercetools/commercetools-sunrise-java#520]
We encountered the following with v0.9.0:
When displaying the price, the default ProductVariantBeanFactory.fillPriceInfo() method uses MoneyContext.of(currency, locale) in order to determine the correct currency and number format to display.
However, it uses userContext.locale() to provide the locale. In our case, this returns "de" as it is the first locale in the list.
Unfortunately, for this locale it can't find the correct currency Symbol "€" and therefore it falls back to the valid code "EUR". 

For now we can work around that e.g. by overriding and explicitly providing Locale.GERMANY - but it would be nice if this gets fixed as the code plainly is designed to return currency symbols (e.g. [PriceFormatter.format()](https://github.com/commercetools/commercetools-sunrise-java/blob/5eccd16ee2365328d544d2aaa80313dce42d3dad/common/app/com/commercetools/sunrise/common/utils/PriceFormatterImpl.java#L25)).

**Comment by lauraluiz** [comment]
@fhaertig definitely we have some work to do with the MoneyContext class and the way it is provided. The currency symbol is a very well-known issue, since it can't determine the symbol of a currency without knowing the country, and yet for languages we usually don't need the country so it's skipped.

We already have the solution in mind but we need to rework all price classes. In any case, it is up in our priority list: https://github.com/commercetools/commercetools-sunrise-java/issues/432

I'll close this issue, if you have anything to add you can continue in the other issue.
