### ISSUE TITLE
Recover/reset password

### ISSUE THREAD

**Issue by lauraluiz** [commercetools/commercetools-sunrise-java#532]

**Comment by Oehmi** [comment]
**Basic user story**
_As a_ customer
_I want to_ reset my password via the Forget Password functionality
_in order to_  log in to the shop again after forgetting my password. 

**Current situation**
The "Forgot Password" link is currently available in Sunrise, but not functional.

**Desired solution**

For this feature, we would like to be able to set a new password using a token within Sunrise. 
- [ ] Once the "Forgot Password" link is clicked, the user should be able to enter his email and submit it. The token is generated; an event should initialize sending the email to the customer.

In the email sent, the user will receive a link to reset his password. 

- [ ]  There should then also be a page template where the user can enter the new password in twice, and after submitting it, the token should be validated again (valid token/user) 

- [ ]  After validation of the new password, a redirect to the login page should take place, so that the user can login to the shop with his/her new password.

**Comment by selo-ecube** [comment]
Will this feature also be part of a v0.2x release or will it only be part of v1.0.0-M6? (I don't intend to ask for the feature being released via v0.2x. I just want to clarify where we can get the implementation from.) Thanks!

**Comment by lauraluiz** [comment]
Yes, it will @selo-ecube. Was planning to work on it between today and tomorrow to have it ready for release this week :)

**Comment by lauraluiz** [comment]
@selo-ecube finally it's here, the forget password functionality on [v0.22.0](https://github.com/commercetools/commercetools-sunrise-java/releases/tag/v0.22.0). Sorry for the delay, we wanted to ensure the released feature was thoroughly tested, since it involved SMPT servers. Hopefully we didn't cause you any inconvenience :)

**Comment by selo-ecube** [comment]
Thanks! (No it didn't cause any inconvenience.)
