### ISSUE TITLE
Customer Login always leads to CustomerNotFoundException

### ISSUE THREAD

**Issue by fhaertig** [commercetools/commercetools-sunrise-java#545]
We recently upgraded to framework v0.14.0. Due to the changes (e.g. CustomerInSession), a Customer is not able to login anymore. 
After entering valid credentials, the **SunriseFrameworkMyAccountController** is producing a CustomerNotFoundException, since the CustomerFinderBySession returns null. As far as I understood it, the **SunriseLogInController** is never writing any id to the session, therefore the login can't happen. The Bug can be fixed by overriding e.g. the handleSuccessfulAction in our own LogInController (nothing else is overwritten):

`    @Override`
`        public CompletionStage<Result> handleSuccessfulAction(final LogInFormData formData, final Void context, final CustomerSignInResult result) {`
`            CustomerSignInResultLoadedHook.runHook(hooks(), result);`
          **customerInSession.store(result.getCustomer());**
 `           return redirectToMyPersonalDetails();`
 `       }`

This should be the default behaviour of sunrise, as it was before the release.

**Comment by lauraluiz** [comment]
@fhaertig you spotted well the cause why it is not working for you. The reason is because the way cart/customer session is handled changed in v.0.12.1, where the storing of session information was triggered by Hooks.

The release notes explained this, but unfortunately did not help much migrating. I've changed a bit the wording and hopefully now is clearer: https://github.com/commercetools/commercetools-sunrise-java/releases/tag/v0.12.1

> Overwriting the data in session for Cart and Customer is triggered with Sunrise Components. Register to your [Module.java](https://github.com/commercetools/commercetools-sunrise-java/blob/v0.12.1/app/Module.java#L82-L83) both [`CartComponent`](https://github.com/commercetools/commercetools-sunrise-java/blob/v0.12.1/common/app/com/commercetools/sunrise/shoppingcart/CartComponent.java) and [`CustomerComponent`](https://github.com/commercetools/commercetools-sunrise-java/blob/v0.12.1/common/app/com/commercetools/sunrise/myaccount/CustomerComponent.java) and enable it to the controllers you consider necessary in order to activate them.

Therefore you'll need to add these two components to the Module.java as it shows in the current version: https://github.com/commercetools/commercetools-sunrise-java/blob/v0.14.0/app/Module.java#L82-L83

Let me know if it fixed the problem.

**Comment by fhaertig** [comment]
Yes, this fixes the issue. We missed that release note during migration from v.0.12.0, thank you very much for pointing it out!
