### ISSUE TITLE
SunriseAddProductToCartController can't find existing cart, CartDetailController shows wrong cart

### ISSUE THREAD

**Issue by fhaertig** [commercetools/commercetools-sunrise-java#546]
With framework v.0.14.0, we experience major errors (see also #545). This effects also the cart handling and it seems to be produced by the following bugs: 

1. when a user is signed in and adds a product to a cart, the SunriseAddProductToCartController searches for a cart id in the session. Since this id is never stored in the session, it creates always a new cart for the customer. As a workaround, we override the handleSuccessfulAction() method and add the created cart ourself by calling `cartInSession.store(cart);`

2. This however doesn't fix the cart view (SunriseCartDetailController). Here, the CartFinderBySession is asked for a cart by customer id but never returns the cart belonging to the current customer. I'm not sure where the cause is though, maybe the newly created cart doesn't get a customerId. We also did a workaround for now by implementing our own CartFinderBySession with the following method buildQuery():

`private Optional<CartQuery> buildQuery() {`
`        return cartInSession.findCartId()`
`            .map(this::buildQueryByCartId)`
`            .map(query -> query`
`                .plusPredicates(cart -> cart.cartState().is(CartState.ACTIVE))`
`                .plusExpansionPaths(c -> c.shippingInfo().shippingMethod()) // TODO use run hook on cart query instead`
`                .plusExpansionPaths(c -> c.paymentInfo().payments())`
 `               .withSort(cart -> cart.lastModifiedAt().sort().desc())`
 `               .withLimit(1));`
 `   }`

It would be nice to fix these bugs as we are expecting this to be standard behaviour.

**Comment by selo-ecube** [comment]
To us, it looks like [CartFinderBySession.java#L49](https://github.com/commercetools/commercetools-sunrise-java/blob/f514f49f10d18fad2563037c1dd7e1e47aa20b42/common/app/com/commercetools/sunrise/shoppingcart/CartFinderBySession.java#L49)ff. might be ineffective:

```
.map(customerId -> Optional.of(buildQueryByCustomerId(customerId)))
                .orElseGet(() -> cartInSession.findCartId()
                        .map(this::buildQueryByCartId))
```

There will always be a query based on the customer Id (which might later yield no result) and hence the lambda passed to orElseGet(...) will not be effective.

**Comment by lauraluiz** [comment]
Related to https://github.com/commercetools/commercetools-sunrise-java/issues/545

@fhaertig @selo-ecube please check if the solution in #545 solves this issue too.

**Comment by fhaertig** [comment]
Okay, we now see the correct cart after making the suggested changes from #545. However, the returned cart does not have a value for `customerEmail`. Should this be done by us with e.g. CartCreateCommandHook or are we also missing something?

Also, the note from @selo-ecube is still valid.

**Comment by lauraluiz** [comment]
@fhaertig @selo-ecube the code you posted is a bit misleading because it's missing a part:
```java
return customerInSession.findCustomerId()
                .map(customerId -> Optional.of(buildQueryByCustomerId(customerId)))
                .orElseGet(() -> cartInSession.findCartId()
                        .map(this::buildQueryByCartId))
```
The `orElseGet` happens when the customerId could not be found. So basically it does "find Customer ID, if found build query by customer ID, otherwise find Cart ID and if found build query by cart ID". I'm about to extract some more functionality into functions to avoid future misunderstandings, as it is not good that the method it has more than one nested level, it clearly makes it difficult to understand.

Regarding the `customerEmail`, I've tested it manually (automated tests are coming soon) and it seems to work fine:

The customer email is saved in session here:
https://github.com/commercetools/commercetools-sunrise-java/blob/v0.14.0/common/app/com/commercetools/sunrise/myaccount/CustomerInSession.java#L64

And then added to the cart draft here:
https://github.com/commercetools/commercetools-sunrise-java/blob/v0.14.0/common/app/com/commercetools/sunrise/shoppingcart/CartComponent.java#L79

I checked in the [Playground](https://impex.commercetools.com/playground) and I can see my email in the newly created cart.

I wonder if I missed something else in the Release Notes, but then you wouldn't have everything working correctly except for that.

@fhaertig could you provide more info so that we can track the issue down? For example, check first if the customerEmail is missing from your session cookies. If it's there, then I would suggest to debug the code to find out why the CartDraft is not receiving any email from the session.

**Comment by lauraluiz** [comment]
Ah and make sure you remove all session cookies, as I made the cookie keys configurable, I think I might have changed the default value.

**Comment by fhaertig** [comment]
yes, sorry regarding the CartFinderBySession note - it seems like we got a bit confused by the nested Optional.

I checked again with the missing `customerEmail` and this is how I can reproduce it (using of course the default controller functionality and after cleaning session cookies):

1. Open up shop home and make sure you're not logged in as a user.
2. Go to a product detail page and add the product to your cart.
3. Go to cart detail page and check if the product was successfully added. Check in Playground that the cart has no customerId and customerEmail.
4. Login as a valid user. Check if the session cookie contains correct values for the keys ["sunrise-customer-id", "sunrise-customer-email"] 
5. Go to cart detail page and check again for products - cart should be merged. Check in Playground for the cart -> customerId is now set, but customerEmail is not.

**Comment by lauraluiz** [comment]
@fhaertig the merging of carts happens in the platform, so that's why it's not present in the code.

In order to make sure that the cart contains all desired info we will have to intercept each time a log in or sign up happens and make an additional call to add any missing info (easy with CartComponent#onCustomerSignInResultLoaded method).

I've implemented it already on another branch, but still working on tests. Hopefully I will be able to make the PR today and you can either wait until I release a new version (probably on Friday) or apply the fix yourself :)

**Comment by fhaertig** [comment]
As always, many thanks for the fast reaction! :)
