### ISSUE TITLE
Mini cart does not referesh

### ISSUE THREAD

**Issue by floriansattler** [commercetools/commercetools-sunrise-java#561]
Steps to reproduce:
Use chrome or any other browser.
1. Add a product from PDP to the cart (mini cart contains one item)
2. Click on the back button in your browser.
3. Mini cart shows that there are zero items in the cart (should be one)

**Comment by mmoelli** [comment]
@lauraluiz @ccsalazarr-commercetools Have you had a look at this issue? Can you please mark it either as bug or as enhancement?

**Comment by lauraluiz** [comment]
Sorry, I had a look when it was created and wanted to check something afterwards and then it slipped from my mind.

It's not technically a Sunrise problem, any browser uses the cached page version when you use the back button. Only when you refresh will the page in cache be updated, having everything back to normal. This is an issue that has to be solved on the project using Sunrise.

There are two main solutions that users can do to fix this:

1) Disable all cache (using the `@NoCache` annotation) on all pages where the mini cart is displayed. That's of course dangerous for performance, but at least you can make sure this information is not coming from the cache. This is the currently supported Sunrise option, not ideal. 

2) Having the mini cart generated via AJAX instead of coming from the backend request. That's a purely frontend issue and the best and ideal solution. Sunrise Theme won't support it in the near future because we are focusing on more structural issues at the moment, but it is our target solution in the long term.
